version: '3'
services:
  database:
    image: mysql:8.0
    container_name: team9_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - team9

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team9-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
    command: >
      sh -c "sleep 10 &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    tty: true
    networks:
      - team9

networks:
  team9:
    driver: bridge